wip checkpoint

diff --git a/corezfs b/corezfs
--- a/corezfs
+++ b/corezfs
@@ -1,34 +1,45 @@
 #!/bin/bash
 
-function error_exit {
-	echo "$(basename $0): ${1:-"Unknown Error"}" 1>&2
-	exit 1
-}
+version="v0.1.1"
 
 SPLREPO="https://api.github.com/repos/zfsonlinux/spl/tarball"
 ZFSREPO="https://api.github.com/repos/zfsonlinux/zfs/tarball"
 
-. /usr/share/coreos/release
-. /usr/share/coreos/update.conf
-. /etc/coreos/update.conf
+function log_entry { echo "${1}" 1>&2; [ ! "${2}" ] || exit ${2}; }
+function log_error { log_entry "Error: ${1}" "${2}"; }
+function debug { log_entry "$(set -o posix ; set | sort)"; }
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-BUILDROOT="$DIR/build"
-DEVREPO="http://${GROUP:-stable}.release.core-os.net/$COREOS_RELEASE_BOARD/$COREOS_RELEASE_VERSION/coreos_developer_container.bin.bz2"
-DEVENV="$DIR/coreos_developer_container.bin"
-VERSION="corezfs_${COREOS_RELEASE_BOARD}_${COREOS_RELEASE_VERSION}_${GROUP:-stable}"
-ARCHIVE="${2:-${DIR}/${VERSION}.tar.gz}"
+[ "${EUID}" -eq 0 ] || log_error "$(basename ${0}) must be run as root" 1
 
-function prepare_build_script {
-	echo "Preparing build script"
-	cat > ${BUILDROOT}/opt/usr/local/sbin/build-zfs.sh <<-"EOF"
-	#!/bin/bash
+. /usr/share/coreos/release || log_error "failed to source /usr/share/coreos/release file" 1
+. /usr/share/coreos/update.conf || log_error "failed to source /usr/share/coreos/update.conf" 1
 
-	function error_exit
-	{
-	    echo "$(basename $0): ${1:-"Unknown Error"}" 1>&2
-	    exit 1
-	}
+DIR="$(pwd)"
+BUILDROOT="${DIR}/build"
+VERSION="${COREOS_RELEASE_BOARD}_${COREOS_RELEASE_VERSION}_${GROUP:=stable}"
+DEVREPO="https://${GROUP}.release.core-os.net/${COREOS_RELEASE_BOARD}/${COREOS_RELEASE_VERSION}/coreos_developer_container.bin.bz2"
+DEVENV="${DIR}/coreos_${VERSION}.bin"
+ARCHIVE="${DIR}/corezfs_${VERSION}.tar.gz"
+
+read -d '' help_message <<-EOF
+
+	$(basename ${0}) (${version})
+	    Bash script to build ZFS on Linux (ZoL) on CoreOS
+	
+	Usage:
+	    $(basename ${0}) build
+		$(basename ${0}) install
+	
+	the build command will build it.
+
+	the install command will install it.
+EOF
+
+read -d '' build_script <<-'EOF'
+	#!/usr/bin/env bash
+
+	function log_entry { echo "${1}" 1>&2; [ ! "${2}" ] || exit ${2}; }
+	function log_error { log_entry "Error: ${1}" "${2}"; }
 	
 	mkdir -p /usr/local/src
 	cd /usr/local/src
@@ -36,75 +47,46 @@ function prepare_build_script {
 	emerge-gitclone \
 	&& (. /usr/share/coreos/release; \
 	git -C /var/lib/portage/coreos-overlay checkout build-${COREOS_RELEASE_VERSION%%.*}) \
-	|| error_exit "$LINENO: Error installing emerge-gitclone"
+	|| log_error "$LINENO: Error installing emerge-gitclone" 1
 
 	emerge -gKv coreos-sources \
 	&& gzip -cd /proc/config.gz > /usr/src/linux/.config \
 	&& make -C /usr/src/linux modules_prepare \
-	|| error_exit "$LINENO: Error installing coreos-sources"
+	|| log_error "$LINENO: Error installing coreos-sources" 1
 
 	emerge sys-devel/automake sys-devel/autoconf sys-devel/libtool \
-	|| error_exit "$LINENO: Error installing development tools"
+	|| log_error "$LINENO: Error installing development tools" 1
 
 	mkdir spl \
 	&& curl -L "$SPLREPO" \
 	| tar -zxv -C spl --strip-components=1 \
-	|| error_exit "$LINENO: Error cloning spl repository"
-	cd spl
-	./autogen.sh || error_exit "$LINENO: Error running autogen.sh for spl"
-	./configure || error_exit "$LINENO: Error configuring spl"
-	make -j$(nproc) || error_exit "$LINENO: Error making spl"
-	make install || error_exit "$LINENO: Error installing spl"
-	cd ../
+	|| log_error "$LINENO: Error cloning spl repository" 1
+	(cd spl;
+	./autogen.sh || log_error "$LINENO: Error running autogen.sh for spl" 1
+	./configure || log_error "$LINENO: Error configuring spl" 1
+	make -j$(nproc) || log_error "$LINENO: Error making spl" 1
+	make install || log_error "$LINENO: Error installing spl" 1)
+
 	mkdir zfs \
 	&& curl -L "$ZFSREPO" \
 	| tar -zxv -C zfs --strip-components=1 \
-	|| error_exit "$LINENO: Error cloning zfs repository"
-	cd zfs
-	./autogen.sh || error_exit "$LINENO: Error running autogen.sh for zfs"
+	|| log_error "$LINENO: Error cloning zfs repository" 1
+	(cd zfs;
+	./autogen.sh || log_error "$LINENO: Error running autogen.sh for zfs" 1
 	./configure \
 		--disable-sysvinit \
 		--with-systemdunitdir=/usr/local/etc/systemd/system \
 		--with-systemdpresetdir=/usr/local/etc/systemd/system-preset \
-	|| error_exit "$LINENO: Error configuring zfs"
-	make -j$(nproc) || error_exit "$LINENO: Error making zfs"
-	make install || error_exit "$LINENO: Error installing zfs"
-	EOF
-	chmod +x ${BUILDROOT}/opt/usr/local/sbin/build-zfs.sh
-}
-
-function delete_build_script {
-	echo "Deleting build script"
-	rm -f ${BUILDROOT}/usr/local/sbin/build-zfs.sh
-}
-
-function download_dev_env {
-	echo "Downloading development environment"
-	if [ ! -e "$DEVENV" ]; then	
-		gpg2 --keyserver pgp.mit.edu --recv-keys 48F9B96A2E16137F && \
-		curl -L "$DEVREPO" | tee >(bzip2 -d > "$DEVENV") | gpg2 --verify <(curl -Ls "${DEVREPO}.sig") - \
-		|| error_exit "$LINENO: Error downloading coreos_developer_container from $DEVREPO"
-	fi
-}
-
-function launch_dev_env {
-	echo "Launching development container"
-	sudo systemd-nspawn \
-		--ephemeral \
-		--bind="$BUILDROOT/opt/usr/local:/usr/local" \
-		--overlay="/lib/modules:$BUILDROOT/opt/usr/local/lib/modules:/lib/modules" \
-		--image="$DEVENV" \
-		--setenv="SPLREPO=$SPLREPO" \
-		--setenv="ZFSREPO=$ZFSREPO" \
-		build-zfs.sh \
-		|| error_exit "$LINENO: Error running development container"
-}
+	|| log_error "$LINENO: Error configuring zfs" 1
+	make -j$(nproc) || log_error "$LINENO: Error making zfs" 1
+	make install || log_error "$LINENO: Error installing zfs" 1)
+EOF
 
 function create_systemd_units {
 	echo "Creating Systemd Unit Files"
 	cat > ${BUILDROOT}/opt/usr/local/etc/systemd/system/lib-modules.mount <<-EOF
 	[Unit]
-	Description=ZFS Kernel Modules
+	Description=Mount ZFS Kernel Modules Overlay
 	ConditionPathExists=/opt/usr/local/lib/modules
 	Before=zfs.service
 
@@ -115,7 +97,7 @@ function create_systemd_units {
 	Options=lowerdir=/lib/modules,upperdir=/opt/usr/local/lib/modules,workdir=/opt/usr/local/lib/.modules.wd
 
 	[Install]
-	WantedBy=zfs.service
+	RequiredBy=zfs.service
 	EOF
 
 	cat > ${BUILDROOT}/opt/usr/local/etc/systemd/system/usr-local.mount <<-EOF
@@ -162,31 +144,67 @@ function create_systemd_units {
 
 case "$1" in
 	build)
-		echo "Building ZFS on Linux (ZoL) for CoreOS ($VERSION)"
-		[ "$EUID" -eq 0 ] || error_exit "Script must be run as root"
+		log_entry "Building ZFS on Linux (ZoL) for CoreOS ($VERSION)"
 		
-		rm -rf ${BUILDROOT}		
-		mkdir -p ${BUILDROOT}/{opt/usr/{local/{lib/{modules,.modules.wd},etc,sbin},.local.wd},etc/systemd/{system,system-preset}} \
-		|| error_exit "$LINENO: Error creating overlay directories"
-		prepare_build_script
-		download_dev_env
-		launch_dev_env
-		delete_build_script
+		rm -rf "${BUILDROOT}" && mkdir -p "${BUILDROOT}/usr/local/sbin" \
+		|| log_error "$LINENO: Error creating directory ${BUILDROOT}" 1
+		
+		log_entry "Preparing build script"
+		echo "${build_script}" > "${BUILDROOT}/usr/local/sbin/build-zfs.sh" \
+		&& chmod +x "${BUILDROOT}/usr/local/sbin/build-zfs.sh" \
+		|| log_error "$LINENO: Error creating build script" 1
+		
+		log_entry "Refreshing CoreOS signing key"
+		gpg2 --keyserver pgp.mit.edu --recv-keys 50E0885593D2DCB4 \
+		|| log_error "Failed to update signing key" 1
+
+		if [ ! -r "${DEVENV}.bz2" ]; then
+			log_entry "Downloading development container"
+			curl -L "${DEVREPO}" > "${DEVENV}.bz2" \
+			|| log_error "Failed to download development container" 1
+		fi
+
+		log_entry "Verifying development container signature"
+		gpg2 --verify <(log_entry "Downloading development container signature"
+			curl -L ${DEVREPO}.sig \
+			|| log_error "Failed to download development container signature" 1) "${DEVENV}.bz2" \
+		&& (log_entry "Decompressing development container"
+			bunzip2 "${DEVENV}.bz2" > "${DEVENV}" \
+			|| log_error "Failed to decompress development container" 1)  \
+		|| log_error "Development container signature verification failed for ${DEVENV}.bz2" 1
+
+		log_entry "Launching development container"
+		cmd=build-zfs.sh
+		cmd="bash --login" # uncomment this line to open a shell in the build container instead of running build script
+		sudo systemd-nspawn \
+			--image="${DEVENV}" \
+			--ephemeral \
+			--setenv="SPLREPO=${SPLREPO}" \
+			--setenv="ZFSREPO=${ZFSREPO}" \
+			${cmd} \
+			|| log_error "$LINENO: Error running development container" 1
+		# --overlay="/usr:$BUILDROOT/opt/usr:/usr" \
+		# --overlay="/lib/modules:$BUILDROOT/opt/usr/local/lib/modules:/lib/modules"
+		# build-zfs.sh \
+		# 
+		log_entry "Deleting build script"
+		rm -f ${BUILDROOT}/usr/local/sbin/build-zfs.sh
+
 		create_systemd_units
 		
 		(cd "$BUILDROOT"/opt/usr/local/etc/systemd/system && ls) \
-		| xargs -I {} sudo ln -s /opt/usr/local/etc/systemd/system/{} "$BUILDROOT"/etc/systemd/system/ \
+		| xargs -I {} ln -s /opt/usr/local/etc/systemd/system/{} "$BUILDROOT"/etc/systemd/system/ \
 		|| error_exit "$LINENO: Error creating links to systemd unit files"
 		
 		(cd "$BUILDROOT"/opt/usr/local/etc/systemd/system-preset && ls) \
-		| xargs -I {} sudo ln -s /opt/usr/local/etc/systemd/system-preset/{} "$BUILDROOT"/etc/systemd/system-preset/ \
+		| xargs -I {} ln -s /opt/usr/local/etc/systemd/system-preset/{} "$BUILDROOT"/etc/systemd/system-preset/ \
 		|| error_exit "$LINENO: Error creating links to systemd preset files"
 		
 		(cd "$BUILDROOT" && tar -zcvf "${ARCHIVE}" *)
-		cat <<-EOF
+		cat <<-"EOF"
 		Finished Building ZFS on Linux (ZoL) for CoreOS ($VERSION)
 		Archive file: $ARCHIVE
-		Run 'sudo rm -rf $BUILDROOT' to delete the temporary build directory
+		Run 'rm -rf ${BUILDROOT}' to delete the temporary build directory
 		EOF
 		;;
 	install)
