Added status echo statements

diff --git a/corezfs b/corezfs
--- a/corezfs
+++ b/corezfs
@@ -16,62 +16,65 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 ARCHIVE="${DIR}/${2:-corezfs_$COREOS_RELEASE_BOARD_$COREOS_RELEASE_VERSION_${GROUP:-stable}}.tar.gz"
 
 function prepare_build_script {
-    cat > /opt/usr/local/sbin/build-zfs.sh <<-"EOF"
-    #!/bin/bash
+	echo "Preparing build script"
+cat > /opt/usr/local/sbin/build-zfs.sh <<-"EOF"
+#!/bin/bash
 
-    function error_exit
-    {
-        echo "$(basename $0): ${1:-"Unknown Error"}" 1>&2
-        exit 1
-    }
+function error_exit
+{
+	echo "$(basename $0): ${1:-"Unknown Error"}" 1>&2
+	exit 1
+}
 
-    [ "$EUID" -eq 0 ] || error_exit "Script must be run as root"
+[ "$EUID" -eq 0 ] || error_exit "Script must be run as root"
 
-    emerge-gitclone \
-    && (. /usr/share/coreos/release; \
-    git -C /var/lib/portage/coreos-overlay checkout build-${COREOS_RELEASE_VERSION%%.*}) \
-    ||  error_exit "$LINENO: Error installing emerge-gitclone"
+emerge-gitclone \
+&& (. /usr/share/coreos/release; \
+git -C /var/lib/portage/coreos-overlay checkout build-${COREOS_RELEASE_VERSION%%.*}) \
+||  error_exit "$LINENO: Error installing emerge-gitclone"
 
-    emerge -gKv coreos-sources \
-    && gzip -cd /proc/config.gz > /usr/src/linux/.config \
-    && make -C /usr/src/linux modules_prepare \
-    || error_exit "$LINENO: Error installing coreos-sources"
+emerge -gKv coreos-sources \
+&& gzip -cd /proc/config.gz > /usr/src/linux/.config \
+&& make -C /usr/src/linux modules_prepare \
+|| error_exit "$LINENO: Error installing coreos-sources"
 
-    emerge sys-devel/automake sys-devel/autoconf sys-devel/libtool \
-    || error_exit "$LINENO: Error installing development tools"
+emerge sys-devel/automake sys-devel/autoconf sys-devel/libtool \
+|| error_exit "$LINENO: Error installing development tools"
 
-    mkdir spl \
-    && curl -L https://api.github.com/repos/zfsonlinux/spl/tarball \
-    | tar -zxv -C spl --strip-components=1 \
-    || error_exit "$LINENO: Error cloning spl repository"
-    cd spl
-    ./autogen.sh || error_exit "$LINENO: Error running autogen.sh for spl"
-    ./configure --prefix /usr/local || error_exit "$LINENO: Error configuring spl"
-    make -j$(nproc) || error_exit "$LINENO: Error making spl"
-    make install || error_exit "$LINENO: Error installing spl"
-    cd ../
-    mkdir zfs \
-    && curl -L https://api.github.com/repos/zfsonlinux/zfs/tarball \
-    | tar -zxv -C zfs --strip-components=1 \
-    || error_exit "$LINENO: Error cloning zfs repository"
-    cd zfs
-    ./autogen.sh || error_exit "$LINENO: Error running autogen.sh for zfs"
-    ./configure \
-        --disable-sysvinit \
-        --with-systemdunitdir=/usr/local/systemd/system \
-        --with-systemdpresetdir=/usr/local/systemd/system-preset \
-    || error_exit "$LINENO: Error configuring zfs"
-    make -j$(nproc) || error_exit "$LINENO: Error making zfs"
-    make install || error_exit "$LINENO: Error installing zfs"
-    EOF
+mkdir spl \
+&& curl -L https://api.github.com/repos/zfsonlinux/spl/tarball \
+| tar -zxv -C spl --strip-components=1 \
+|| error_exit "$LINENO: Error cloning spl repository"
+cd spl
+./autogen.sh || error_exit "$LINENO: Error running autogen.sh for spl"
+./configure --prefix /usr/local || error_exit "$LINENO: Error configuring spl"
+make -j$(nproc) || error_exit "$LINENO: Error making spl"
+make install || error_exit "$LINENO: Error installing spl"
+cd ../
+mkdir zfs \
+&& curl -L https://api.github.com/repos/zfsonlinux/zfs/tarball \
+| tar -zxv -C zfs --strip-components=1 \
+|| error_exit "$LINENO: Error cloning zfs repository"
+cd zfs
+./autogen.sh || error_exit "$LINENO: Error running autogen.sh for zfs"
+./configure \
+	--disable-sysvinit \
+	--with-systemdunitdir=/usr/local/systemd/system \
+	--with-systemdpresetdir=/usr/local/systemd/system-preset \
+|| error_exit "$LINENO: Error configuring zfs"
+make -j$(nproc) || error_exit "$LINENO: Error making zfs"
+make install || error_exit "$LINENO: Error installing zfs"
+EOF
     chmod +x /opt/usr/local/sbin/build-zfs.sh
 }
 
 function delete_build_script {
+	echo "Deleting build script"
     rm -f /opt/usr/local/sbin/build-zfs.sh
 }
 
 function download_dev_env {
+	echo "Downloading development environment"
     if [ ! -e "$DIR/coreos_developer_container.bin" ]; then
         url="http://${GROUP:-stable}.release.core-os.net/$COREOS_RELEASE_BOARD/$COREOS_RELEASE_VERSION/coreos_developer_container.bin.bz2"
         gpg2 --recv-keys 48F9B96A2E16137F && \
@@ -83,6 +86,7 @@ function download_dev_env {
 }
 
 function launch_dev_env {
+	echo "Launching development container"
     sudo systemd-nspawn \
         --ephemeral \
         --read-only \
@@ -96,6 +100,7 @@ function launch_dev_env {
 }
 
 function create_systemd_units {
+	echo "Creating Systemd Unit Files"
 cat > /opt/usr/local/etc/systemd/system/lib-modules.mount <<-EOF
 [Unit]
 Description=ZFS Kernel Modules
@@ -152,6 +157,7 @@ EOF
 
 case "$1" in
     "build")
+    	echo "Building ZFS on Linux (ZoL) on CoreOS"
         rm -rf /opt     
         mkdir -p /opt/{modules,.modules.wd,usr/{local/{share/corezfs,sbin,etc/systemd/{system,system-preset}},.local.wd}} \
         || error_exit "$LINENO: Error creating overlay directories"
@@ -164,8 +170,10 @@ case "$1" in
         if [ $2 != "--no-archive" ]; then
             tar -zcvhf "${ARCHIVE}" -C / --exclude=/opt/.modules.wd/* --exclude=/opt/usr/.local.wd opt
         fi
+        echo "Finished Building ZFS on Linux (ZoL) on CoreOS"
         ;;
     "install")
+    	echo "Installing ZFS on Linux (ZoL) on CoreOS"
         if [ -e "$ARCHIVE" ]; then
             tar -zxvhf "$ARCHIVE" -C / \
             || error_exit "$LINENO: Error extracting $ARCHIVE"
@@ -182,6 +190,7 @@ case "$1" in
         
         ls /opt/usr/local/systemd/system/* | xargs systemctl preset || error_exit "$LINENO: Error presetting systemd zfs units"
         systemctl start zfs.target || error_exit "$LINENO: Error starting zfs.target systemd unit"
+        echo "Finished Installing ZFS on Linux (ZoL) on CoreOS"
         ;;
     *)
 cat <<-EOF
